// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5QkYNThzdvKOmk7Tdjl71NVdOtXdK7YE',
    appId: '1:123940476933:web:5e116afb0ae99f6d29a46c',
    messagingSenderId: '123940476933',
    projectId: 'flutter-summer',
    authDomain: 'flutter-summer.firebaseapp.com',
    databaseURL: 'https://flutter-summer.firebaseio.com',
    storageBucket: 'flutter-summer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Dsg1Y1QutAdnaZnTCzv8dNuR_CuiKMA',
    appId: '1:123940476933:android:1823373a5369c93c29a46c',
    messagingSenderId: '123940476933',
    projectId: 'flutter-summer',
    databaseURL: 'https://flutter-summer.firebaseio.com',
    storageBucket: 'flutter-summer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJt8VPzxehcWQDY_pmSkGy7pWKA6UinYs',
    appId: '1:123940476933:ios:084f30c4eb5293b429a46c',
    messagingSenderId: '123940476933',
    projectId: 'flutter-summer',
    databaseURL: 'https://flutter-summer.firebaseio.com',
    storageBucket: 'flutter-summer.appspot.com',
    iosClientId: '123940476933-6tc38859hdnjqn5fj07vpkds6g8nlste.apps.googleusercontent.com',
    iosBundleId: 'com.codingminds.flutterAppReciples',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJt8VPzxehcWQDY_pmSkGy7pWKA6UinYs',
    appId: '1:123940476933:ios:084f30c4eb5293b429a46c',
    messagingSenderId: '123940476933',
    projectId: 'flutter-summer',
    databaseURL: 'https://flutter-summer.firebaseio.com',
    storageBucket: 'flutter-summer.appspot.com',
    iosClientId: '123940476933-6tc38859hdnjqn5fj07vpkds6g8nlste.apps.googleusercontent.com',
    iosBundleId: 'com.codingminds.flutterAppReciples',
  );
}
